/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function captureNextWindowFirstCursorEnter(callback: (x: number, y: number) => void): void

export declare function dragWindow(handle: Buffer): void

export declare function getLastCreatedWindowId(): string | null

export declare function isWayland(): boolean

export declare function isX11(): boolean

export declare function setInputRegion(windowHandle: string | Buffer, rects?: { x: number, y: number, w: number, h: number }[] | null): boolean
